### ISSUE TITLE
Does this work on symfony 5 project?

### ISSUE THREAD

**Issue by njsa04** [tmrdh/symfony-helper#9]
I installed in vscode and nothing seems to show for DQL auto completion.

**Comment by tmrdh** [comment]
It worked some months ago.

Guess it's time to test it.

**Comment by tmrdh** [comment]
Autocompletion for DQL works on my toy symfony 5 and 5.1 projects.

It seems I need more info:
* what's your operating system?
* what's version of globally installed php-interpreter?
* can you share composer.json (and composer.lock)?

Also in coming week I am going to think about self-diagnostic and error reporting for extension.

**Comment by tmrdh** [comment]
I am sorry. I am dropping this project.
